Post alpha fixes
ITI/searcch pull request #28
Opened 2021-03-15 21:03 UTC by Teesh

Fix HTML5 API config for Nuxt
Fix visual errors for short form artifacts
Add advanced queries with types
Add pagination (needs backend changes to be completely proper implementation)

2021-03-15 23:44 UTC, timyardley requested changes
Was .env stub deleted intentionally? If not, that should be reverted.

2021-03-15 23:44 UTC, timyardley commented on pages/search.vue
> +                  label="Orginization"
Typo

2021-03-15 23:44 UTC, timyardley commented on pages/search.vue
> +                  placeholder="Kevin Bacon, Shaquille O'Neil"
Consider a more relevant placeholder text here

2021-03-15 23:44 UTC, timyardley commented on pages/search.vue
> +        //   payload.orginization = this.advanced.query
Does the map handle these? Variables are different, but typo here as well... and if they aren't used, should be removed.

2021-03-15 23:44 UTC, timyardley commented on store/artifacts.js
> +    commit('SET_RELEVANCE_SCORES', relevantScores(state.artifacts))
I think the relevance score stuff is all deprecated now. Should it just be removed?

2021-03-15 23:44 UTC, timyardley commented on store/artifacts.js
> +    a = await this.$knowledgeGraphSearchRepository.index({
Since the zenodo query is removed, this should be remapped as well to something more relevant, like backendRepository or something.

2021-03-22 20:10 UTC, Teesh commented on pages/search.vue
> +        //   payload.orginization = this.advanced.query
Is the question "Does map actually change it to lower case?", then yes it does. Otherwise, not sure what you're asking there.

2021-03-23 13:44 UTC, timyardley requested changes
see comments

2021-03-23 13:44 UTC, timyardley commented on .env
> +ZENODO_API_URL="https://zenodo.org/api/"
the ZENODO environment variables can be removed in the next round

2021-03-23 13:44 UTC, timyardley commented on store/artifacts.js
> +      a = await this.$knowledgeGraphRecordRepository.show(payload.id)
This should be artifactRecordRepository instead

2021-03-23 13:44 UTC, timyardley commented on store/artifacts.js
> +      commit('SET_ARTIFACT', renameKeys({ doi: 'id' }, a))
renameKeys isn't likely needed anymore?

2021-03-23 13:44 UTC, timyardley commented on store/artifacts.js
> +      commit('SET_ARTIFACT', renameKeys({ doi: 'id' }, a))
that may require changing parameters elsewhere though, as I think DOI is passed around at the moment still rather than ID

2021-03-23 13:49 UTC, Teesh commented on store/artifacts.js
> +      commit('SET_ARTIFACT', renameKeys({ doi: 'id' }, a))
I believe I had removed those doi keys early in the dev process

2021-03-23 19:10 UTC, timyardley approved these changes

2021-03-23 19:10 UTC, merged